FROM python:3.11-slim
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY poll_travel_times.py .
COPY starting-points.json .
CMD ["python", "poll_travel_times.py"]
