// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://jqnxqvhofloixfngvmzk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpxbnhxdmhvZmxvaXhmbmd2bXprIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAyOTA2NzcsImV4cCI6MjA2NTg2NjY3N30.3LuohjtvUZ-rxyV-LW7cSxEjb40rhjXeWxih1vqN-wo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);